elixir-mint/mint

lib/xhttp1/conn.ex
test/test_helper.exs
test/xhttp1/conn_properties_test.exs
test/xhttp1/conn_test.exs

\cc @fishcakez @josevalim 
Barebones for now, but I think it's all we need for HTTP/1 tests.

Use a real TCP socket in HTTP/1 tests

---

lib/xhttp1/conn.ex

This PR fixes a case when a request has been served, there is a pause, and the server explicitly closes the TCP connection.  Previously, receiving a `:tcp_closed` or `:ssl_closed` message when the conn's `request` was nil would raise an error.

Handle case when HTTP 1.x server returns response, pauses, then closes connection

---

lib/xhttp/transport.ex
lib/xhttp/transport/ssl.ex
lib/xhttp/transport/tcp.ex
lib/xhttp/util.ex
lib/xhttp1/conn.ex
lib/xhttp2/conn.ex
lib/xhttpn/conn.ex
test/xhttp1/conn_properties_test.exs
test/xhttp1/conn_test.exs
test/xhttp1/integration_test.exs
test/xhttp2/conn_test.exs
test/xhttpn/integration_test.exs

This is the first step towards abstracting transports so that we can use conns as transport (for proxying). This PR only adds a `XHTTP.Transport` behaviour and wraps `:ssl` and `:gen_tcp` in the right modules implementing the behaviour. The next step would be to change the behaviour so that functions are stateful: right now the socket doesn't get changed so the change would be minimal but it will be very important in the future when we have a conn transport.
\cc @josevalim, if you want to take a peek as well :)

Introduce a XHTTP.Transport behaviour

---

lib/xhttp/transport.ex
lib/xhttp/transport/ssl.ex
lib/xhttp/transport/tcp.ex
lib/xhttp1/conn.ex
lib/xhttp2/conn.ex
test/xhttp1/conn_properties_test.exs
test/xhttp1/conn_test.exs
test/xhttp2/conn_test.exs

I left some operations (like `getopts` and `setopts`) stateless for now as I don't think we'll need to make them stateful. Also, I left TCP/SSL messages untouched for now as I think we'll need to add callbacks for streaming messages (so that for example a proxy conn transport can delegate the streaming to the underlying TCP/SSL transport).
\cc @josevalim as always <3

Make transport operations stateful

---

lib/xhttp/transport/ssl.ex
test/support/xhttp/wildcard_san.pem
test/xhttp/transport/ssl_test.exs

Workaround for https://bugs.erlang.org/browse/ERL-542
This also always uses the packaged `pkix_verify_hostname` function, regardless of whether the function is available and activated in the current OTP version.

Support wildcards in certificate SAN extension

---

lib/xhttp/util.ex

I realized that the socket will be handled in the callers ([`XHTTP1.Conn`](https://github.com/ericmj/xhttp/blob/116b93a68ec7cd60db00e7da5c6490ea7356f63b/lib/xhttp1/conn.ex#L102) and [`XHTTP2.Conn`](https://github.com/ericmj/xhttp/blob/116b93a68ec7cd60db00e7da5c6490ea7356f63b/lib/xhttp2/conn.ex#L329)), so perhaps there's no need to close it twice or did I miss anything?

Remove duplicate socket closing statement

---

README.md
lib/xhttp1.ex
lib/xhttp2.ex
lib/xhttp_core/conn.ex
lib/xhttp_core/transport.ex
lib/xhttp_core/transport/ssl.ex
lib/xhttp_core/transport/tcp.ex
lib/xhttp_core/tunnel_proxy.ex
lib/xhttp_core/unsafe_proxy.ex
lib/xhttp_core/util.ex
lib/xhttpn.ex
test/support/xhttp2/test_helpers.ex
test/xhttp1/conn_properties_test.exs
test/xhttp1/conn_test.exs
test/xhttp1/integration_test.exs
test/xhttp2/conn_test.exs
test/xhttp2/integration_test.exs
test/xhttp_core/transport/ssl_test.exs
test/xhttp_core/tunnel_proxy_test.exs
test/xhttp_core/unsafe_proxy_test.exs
test/xhttpn/integration_test.exs

Remove Conn from module names.
Move XHTTP to XHTTPCore.

Change module names

---

lib/xhttp.ex
lib/xhttp/tunnel_proxy.ex
lib/xhttp/unsafe_proxy.ex
lib/xhttp1.ex
lib/xhttp2.ex

We're now missing an "Architecture" page in the docs as far as documentation goes.

Refactor the docs and move most of them to XHTTP

---

lib/xhttp.ex

We can start without this I think, and possibly add it later on based on user needs.

Remove XHTTP.get_transport/1

---

lib/mint/http.ex
mix.exs
pages/Architecture.md

This will not show up in the docs until #65 is merged, otherwise we would have conflicts in the docs configuration in the `mix.exs` file.

Add the start of an "Architecture" page in the docs

---

lib/mint/core/transport/ssl.ex
mix.exs

In order to allow users to use a custom CA trust store without carrying around an unnecessary dependency, the `castore` dependency should be optional.
Perhaps a note should be added to the README, suggesting people add `castore` while adding `mint` to their project unless they intend to use their own trust store.

Optional castore

---

lib/mint/http.ex

See #79
If this is too much to document inline in `Mint.HTTP.connect/3,4` then perhaps we can define a custom type for `:transport_opts` and move the new section to a typedoc. I imagine documenting them under `Mint.Core.Transport.{TCP, SSL}` instead is not desirable.

Document transport options

---

lib/mint/core/transport.ex
lib/mint/core/transport/ssl.ex
lib/mint/core/transport/tcp.ex
lib/mint/http1.ex
lib/mint/http2.ex
lib/mint/negotiate.ex
lib/mint/tunnel_proxy.ex
lib/mint/types.ex

Transports are not public so they should not be leak through the API alongside schemas. Also fixes a issue in HTTP2 where the `:scheme` header can have confusing behavior.

Hide transport modules

---

lib/mint/http.ex

To match
> Always returns `{:ok, conn}` where `conn` is the updated connection.

Fix "Mint.HTTP.close/1" example

---

lib/mint/http1.ex

There is nothing in the spec saying this is prohibited.
From https://github.com/ericmj/mint/issues/90.

Don't check if request body is sent before receiving response

---

lib/mint/http.ex
lib/mint/http2.ex
lib/mint/types.ex
test/mint/http2/conn_test.exs
test/mint/http2/integration_test.exs

This PR adds support for HTTP/2 [server push](https://en.wikipedia.org/wiki/HTTP/2_Server_Push). @josevalim and @ericmj, please take a look at the bottom of this text to help decide the API of the new request introduced in this PR.
Server push works like this:
* Client sends a normal request, say on stream ID 3.
* Server replies normally to the request on stream ID 3 plus it sends a `PUSH_PROMISE` frame on stream ID 3. This frame contains **request headers**, like `:method` and `:path`. Say that the server sends headers `[{":method", "GET"}, {":path", "/style.css"}]`. This is the server saying to the client: "I suspect you're going to do this request identified by these request headers (`GET /style.css` in our case), so I will later send you the response to this request directly without …

Add support for HTTP/2 server push

---

lib/mint/http2.ex

Closes #96.
Before this commit, we were not correctly handling all errors from `stream/2` and sometimes we would lose responses. We were sometimes throwing without responses and sometimes with responses from inside `handle_data/3` and its nested calls, and catching in `stream/2`. Now instead, we're catching inside `handle_data/3` so that we always re-throw  with all the responses we have at that moment.

Improve error handling in Mint.HTTP2.stream/2

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs
test/support/mint/http2/test_server.ex

This is a little bit of a mess but it improves things. The idea is that there are really two "closed" states: the first one is when the server closes via `RST_STREAM` or when the server sends a frame with the `END_STREAM` flag set. In those cases, really we can throw away the stream because if the server then sends significant frames (`HEADERS`/`DATA`) on that stream we're supposed to error out. The trickier case is when we close the stream ourselves (see `cancel_request/2`): in those cases, the server is allowed (for a "short period" according to the spec) to still send `DATA`/`HEADERS` frames on the stream because it might have sent them before receiving our `RST_STREAM`. For those cases, for now I added a `:closed_by_us` stream state and when we receive frames on a `:closed_by_us` …

Improve handling of frames coming in different states

---

lib/mint/core/transport/ssl.ex
lib/mint/core/transport/tcp.ex
test/mint/http1/integration_test.exs

The previous code would pass the `timeout` option to :gen_tcp or :gen_ssl,
neither of which support that as a keyword option.

correctly return timeout errors when connecting

---

test/mint/http2/conn_test.exs
test/support/mint/http2/test_server.ex

Sometimes we would be okay with frames coming to the server after the test was done. This way we wait for the server to confirm that no data is left and no frames are left to handle.

Improve HTTP/2 test server

---

lib/mint/http.ex

I think these return values were switched in the documentation

Change order of conn and request_ref in docs

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs
test/support/mint/http2/test_server.ex

Closes #108.
I'm not 100% sure we want to do this since performance-wise it's not optimal as we can just close the socket and not care, but the protocol says we should 🤷‍♀️ 
One thing to note, I changed the test server so that instead of having a passive socket where we have to do `recv` on it, we have an active socket and use `assert_receive`. I did this because otherwise the test for `close/1` couldn't verify the GOAWAY frame was received by the server, since `close/1` would close the socket and we wouldn't be able to `recv` anything. On the bright side, seems like we came up with a good abstraction and set of helpers since the change to the test server was really minimal :)

Send a GOAWAY frame when closing an HTTP/2 connection

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs

Closes #118.
Before this change, we stored the client settings and the server settings at the same level in the connection, with a weird naming scheme and generally a pretty confusing approach. This change introduces the keys `:client_settings` and `:server_settings` to the `Mint.HTTP2` connection struct so that it's always crystal-clear which one we're referring to.

Improve storing of HTTP/2 client vs server settings

---

.formatter.exs
test/mint/http2/conn_test.exs

This macro hides the call to `recv_next_frames/1`. The benefit of doing this is that we can infer the number of frames we expect by the length of the list of frames that we pass to the `assert_recv_frames/1` macro. Plus, when we know that `assert record() = ...` works correctly, we can replace it in only one place (inside the new macro).
@ericmj I am not sure this is a good idea and I'm not sure that the magic introduced by this is worth introducing. The tests might look better but maybe it's hard to know what's going on. Would love the opinion of a fresh set of eyes :)

Refactor HTTP/2 tests with assert_recv_frames

---

lib/mint/http1/request.ex
test/mint/http1/request_test.exs

RFC 2616 and 7230 state that header keys should be treated as case-insensitive. This change lowers headers keys before the defaults are added, so parsed in headers in a different case are not duplicated.
This change only applies to HTTP/1, but I believe something similar should be done for HTTP/2 (even though HTTP/2 headers should only be lower case). The code uses the `Mint.HTTP1.Parser.lower/1` function though. Maybe that should be moved to `Mint.Core.Util`?

Treat HTTP/1 header keys as case-insentive when adding defaults

---

lib/mint/http1.ex
lib/mint/http1/parse.ex
lib/mint/http1/request.ex
test/mint/http1/parse_test.exs
test/mint/http1/request_test.exs

I added more information to the `:invalid_request_target` and `:invalid_content_length_header` errors.

Improve a couple of HTTP/1 header-related errors

---

lib/mint/http1/parse.ex
test/mint/http1/parse_test.exs

Per RFC 7230:
```
Each header field consists of a case-insensitive field name followed
by a colon (":"), optional leading whitespace, the field value, and
optional trailing whitespace.
```

Strip whitespace when parsing content-length header

---

lib/mint/http1/request.ex
test/mint/http1/request_test.exs

Closes #110.
Before this change, we only checked that a HTTP/1 request target only contained chars that are allowed unescaped. This means that the target validation failed when escaped characters `%xx` were in the validated URL. With this change, we allow chars that are allowed unescaped plus `%xx` escaped chars.

Fix target validation when building HTTP/1 requests

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs

Closes #125.
This function lets you read the window size of either the connection or a single request on HTTP/2 connections. It's HTTP/2 specific.
I'm not sure if this is the right interface. For example, with this there's no way to check what the default window size is for a new request (you can only check the window size of a request if you opened it as a streaming body request). Maybe we can add `:default` to the `:connection | {:request_ref, _}` argument.
I think this function is important because people can choose to split a body in some sensible way when they know the right window size.

Introduce Mint.HTTP2.get_window_size/2

---

lib/mint/http1.ex
lib/mint/http1/request.ex
test/mint/http1/request_test.exs

Right now we throw errors from the `Mint.HTTP1.Request` module and catch them in the `Mint.HTTP1` module. With this change, we catch right in the `Request` module so that it's easier to reason about boundaries between the two modules.

Don't propagate throws outside of the Mint.HTTP1.Request module

---

lib/mint/http1.ex
lib/mint/http1/parse.ex
test/mint/http1/parse_test.exs

Closes #126.
I also removed cross-module throw/catch instances coming from the `Mint.HTTP1.Parse` module, similar to what was done in #136.

Simplify HTTP/1 header parsing and test it through property-based testing

---

lib/mint/http1.ex
lib/mint/http1/parse.ex
test/mint/http1/parse_test.exs

Closes #138.
I removed all throw/catches in `Mint.HTTP1.Parse` as they were unnecessary. I also improved the `:invalid_token_list` error when parsing HTTP/1 header values so that it shows the offending string. I finally added formatting to the `:invalid_token_list` and `:empty_token_list` errors in `Mint.HTTP1`.

Simplify and improve errors in Mint.HTTP1.Parse

---

lib/mint/transport_error.ex

Part of #131, starting out small by documenting the `Mint.TransportError` module and the possible transport error reasons.

Document transport errors in Mint.TransportError

---

lib/mint/http1.ex
lib/mint/http2.ex
lib/mint/http2/frame.ex
lib/mint/http_error.ex
lib/mint/tunnel_proxy.ex
test/mint/http2/conn_test.exs
test/mint/http2/frame_test.exs

@ericmj we need to discuss `TunnelProxy` errors. We can
1. make a `Mint.ProxyError`. It can use `Mint.HTTPError` to format the inner error but add some proxy-specific stuff.
2. wrap all `Mint.HTTPError` errors in `TunnelProxy` by changing the formatter module to `TunnelProxy` and the reason to `{:proxy, original_reason}`. Then we tell users that all reasons documented for `Mint.HTTPError` (for HTTP/1) can also come wrapped inside a `{:proxy, _}` tuple. This avoids introducing a third error type users need to care about, but it's a bit messier with the recursive `{:proxy, reason}` error reason.
Wdyt? Any other ideas?

Clean up and improve HTTP error reasons and document them

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs

Just improving the errors for now, still haven't fixed whether we should always return `:error` or sometimes `:ok` from `stream/2`.

Improve handling of GOAWAY/RST_STREAM frames with better errors

---

lib/mint/unsafe_proxy.ex

@ericmj I'm not sure that the module here is always `Mint.HTTP1` but we **are** calling `Mint.HTTP1.connect/4` directly. I'm doing this change because it fixes a Dialyzer warning about breaking the opacity of the `Mint.HTTP1` struct. Wdyt?

Don't break opaque type boundaries in Mint.UnsafeProxy

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs

Before this commit, we had a bug when sending HTTP/2 requests with a body exceeding the max window size of either the stream or the connection. Basically, we were sending a HEADERS frame and only then checking for the window size and possibly error out. This meant that sending a request that exceeded the window size resulted in sending the HEADERS and then erroring out, leaving the request in an open state on the server.
With this commit, we build the payload for HEADERS and DATA without sending it right away, and send them together if everything is correct (which also leads to an optimization since we do only one socket send call instead of two when sending requests with headers and body).
I also fixed a small bug when checking the window size: before we were checking if the size of the …

Fix bug with HTTP/2 requests exceeding window size

---

lib/mint/http2.ex

In the HTTP/2 handshake, we expect the server to send a SETTINGS frame right after connecting to it and sending it the connection preface. However, the server can also send a GOAWAY and we were not handling that. Now, we handle the server sending either SETTINGS, GOAWAY, or any other frame with a more graceful error.
Tests for this are just horrible so let's skip them for now.

Fix a bug in the HTTP/2 handshake

---

lib/mint/http1.ex

Turns out that turning the accumulated data into iodata is a PITA because we check the size of the accumulated data quite often with `byte_size`, which then becomes expensive to do. Wdyt @ericmj?

Remove a TODO in Mint.HTTP1

---

lib/mint/core/util.ex
lib/mint/http1/parse.ex
lib/mint/http1/request.ex
lib/mint/http1/response.ex
lib/mint/http2.ex
lib/mint/http2/hpack/table.ex
test/mint/http2/hpack/table_test.exs
test/mint/http2/hpack_test.exs
test/mint/http2/integration_test.exs

Before this commit, we would insert headers in the HPACK table without downcasing their name, and we would look up headers without downcasing their name either. With this commit, we downcase header names (since they're case insensitive) before inserting/looking up in the HPACK table.
Closes #171.
@ericmj not sure if there's a better or more efficient way of doing this. We might downcase at the boundary when headers are given to Mint but it's pretty much the same thing I think.

Downcase headers when inserting/fetching in HPACK

---

lib/mint/core/conn.ex
lib/mint/http.ex
lib/mint/http1.ex
lib/mint/http2.ex

We should not expose the socket in order to avoid users messing with it. We do need to be able to retrieve the socket from the connections though because we use that when proxying.

Make Mint.HTTP*.get_socket/1 private

---

lib/mint/core/conn.ex
lib/mint/core/transport.ex
lib/mint/core/transport/ssl.ex
lib/mint/core/transport/tcp.ex
lib/mint/http.ex
lib/mint/http1.ex
lib/mint/http2.ex
lib/mint/unsafe_proxy.ex
test/mint/http1/conn_properties_test.exs
test/mint/http1/conn_test.exs
test/mint/http2/conn_test.exs
test/support/mint/http1/test_server.ex
test/support/mint/http2/test_server.ex

This PR adds support for "passive mode" to the connections. The `:mode` option can be used when connecting to set the mode to `:active` (default) or `:passive`. `set_mode/2` can be used to change the mode of a connection. `recv/3` can be used in passive mode to receive data from the socket.
Closes #170.

set_mode/2 and recv/3

---

lib/mint/http1.ex
lib/mint/http2.ex

Any direct operation comes already with wrapped error,
there is no need to wrap it again.

Remove double wrapping of transport error by receive

---

lib/mint/core/util.ex
lib/mint/http1.ex
lib/mint/http2.ex

If the existing body buffer is empty, we can safely set the incoming body to
be the initial state of that buffer. This prevents a rather slow
allocation from taking place.
In my testing in a database driver, this speeds up the query's
response processing by over two seconds.

Prevented unnecessary buffer allocation

---

lib/mint/http1.ex
lib/mint/http1/request.ex
test/mint/http1/conn_test.exs
test/mint/http1/request_test.exs
test/support/mint/http1/test_server.ex

Based off of @ericmj's work, I:
* moved all the request header handling logic from `HTTP1.Request` to `HTTP1`. This means that now `Request` is really dumb and its only job is to encode method/path/headers/body. Easy to test and reason about. I love it.
* handled the case where a user already has a `transfer-encoding` header but it doesn't contain `chunked` or `identity`
* added tests for all of this stuff

Add support for chunked transfer-encoding in HTTP/1 requests

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs

`Mint.HTTP2.connect/4` (which calls `initiate/5`) was not catching thrown errors from functions used inside it (such as `apply_server_settings`). This commit fixes that and adds the stub of a test (read test comment for more explanation on why it's a stub).

Catch connection errors in Mint.HTTP2.connect/4

---

mix.exs
pages/Decompression.md

Resolves #183 
This adds a guide on how to deal with compressed response bodies.
[view rendered guide](https://github.com/dbernheisel/mint/blob/db-add-decompression-guide/pages/Decompression.md)
I also have a small [example repo](https://github.com/dbernheisel/mint_decompression_example) if anyone wants to see code that decompresses `gzip` and `deflate` responses (though it's really difficult to find a live example of a server that serves up using `deflate`, so only `gzip` is tested).
I think it's possible to decompress the gzipped data as it comes, opposed to all at once at the end, but I'll reserve that for another PR.

Add decompression guide

---

lib/mint/http.ex

Closes #189.
I think we should not touch the `te` header ourselves. After all, Mint supports trailing headers in responses but maybe the user doesn't want to let that know to the server. I'd rather have the user explicitly use `te: trailers` in that case. Thoughts @ericmj?

Add documentation about the TE header

---

lib/mint/core/util.ex
lib/mint/http1.ex
lib/mint/http2.ex
test/mint/http1/conn_properties_test.exs
test/mint/http1/conn_test.exs
test/mint/http2/conn_test.exs

Closes #188.
Now we:
* error out if the user tries to send an unallowed trailing header (returning a new error)
* remove all unallowed trailing headers from response headers (for security reasons)

Handle unallowed trailing headers

---

pages/Architecture.md

GenServer’s `init` callback expects `{:stop, reason}` during failures.
Current example returns `{:error, reason}` which logs an inexact error.
```
** (EXIT from #PID<0.182.0>) shell process exited with reason: bad return value: {:error, %Mint.TransportError{reason: :timeout}}
```

Fix architecture example

---

lib/mint/core/util.ex
lib/mint/http1.ex
test/mint/http1/conn_test.exs

I basically did the same thing as jmmk did here: #200 but for HTTP1.

Add port to host header if it is not the default one for the scheme (HTTP1)

---

lib/mint/http.ex
lib/mint/http1.ex
lib/mint/http2.ex
lib/mint/tunnel_proxy.ex
test/mint/http1/conn_test.exs
test/mint/http2/conn_test.exs
test/mint/http2/integration_test.exs

We want to enforce the body so that in the future we can add options as the sixth argument.

Deprecate request/4

---

lib/mint/http2.ex
test/mint/http2/integration_test.exs

Mint does not support protocol negotiation on TCP connections (RFC7540 3.2)
so for now we assume the protocol is HTTP/2 in the Mint.HTTP2 module.

Assume HTTP/2 protocol on TCP connections

---

README.md

This PR adds badges for hexdocs.pm and hex.pm to the README:
No code was harmed.

Add hexdocs.pm and hex.pm badges to README.md

---

.github/workflows/main.yml

`mix deps.compile` was running in the default :dev env, and so when we run `mix test` it compiled everything again in :test as you can see here: https://github.com/elixir-mint/mint/runs/409356642?check_suite_focus=true
An alternative would be to do `MIX_ENV=test mix deps.compile` or maybe `MIX_ENV=test mix compile` as a step between deps and running tests.

Remove compilation from "Install deps" CI step

---

lib/mint/http.ex
lib/mint/http1.ex
test/mint/http1/conn_test.exs

Closes #238.
This is only for HTTP/1.

Make empty chunk a no-op for stream_request_body/3

---

lib/mint/http.ex

Remove mention of `t:socket_message/0`

---

test/mint/integration_test.exs
test/mint/tunnel_proxy_test.exs

Closes #240.
Using https://httpstat.us instead of httpbin.org, since it seems reliable and supports HTTP/1 only. I say we go for this for now and if it breaks again we evolve :)
Thanks @prodis for the suggestion!

Move some HTTP/1 tests to httpstat.us

---

.github/workflows/main.yml
lib/mint/core/transport/ssl.ex
test/mint/http1/integration_test.exs

See #259
Note that this is a bit of a departure from the earlier Mint approach to `:ssl`: instead of always using the `:mint_shims` module, even on new OTP versions, we now leave hostname verification to OTP on >=20. We still use Mint's own hostname matching function, which is a subset of OTP's (as described in the comments).
I think this is a good first step in adopting OTP built-in defaults where possible, which are fine for newer versions, and only using the shims for really old OTP versions (until support for them is retired).

Fix wildcard cert verification on OTP 23

---

pages/Decompression.md

Function `decompress_data/2` delegates the real work via `Enum.reduce` to `decompress_with_algorithm/2`.

Fix function names for decompression guide

---

lib/mint/http1.ex
lib/mint/http2.ex
test/mint/http1/conn_test.exs

There is one failing test but I believe the test is wrong. We are transferring the test to another process and then trying to stream its response, which fails when trying to set it back to active mode. I want to change the test but I would like confirmation before.

Fix connection closed errors not propagating, closes #279

---

lib/mint/core/transport/ssl.ex

It seems to be working correctly in OTP 23 now so it should be safe to add.

Add TLS 1.3 to default versions

---

lib/mint/http1.ex
lib/mint/http2.ex
test/mint/http1/conn_test.exs
test/mint/http2/conn_test.exs

I was playing with the new :socket inet_backend and encountered the following MatchError:
```
** (MatchError) no match of right hand side value: {:error, :closed}
(mint 1.2.0) lib/mint/http1.ex:837: Mint.HTTP1.internal_close/1
(mint 1.2.0) lib/mint/http1.ex:180: Mint.HTTP1.close/1
```
While `:gen_tcp.close/1` will always return `:ok`, no matter what, the new `:socket.close/1` can return an error tuple.
https://erlang.org/doc/man/gen_tcp.html#close-1
https://erlang.org/doc/man/socket.html#close-1
Perhaps you would prefer to add a Logger.debug message when `conn.transport.close/1` did return an error?

Ignore return value of transport.close/1, for compatibility with new inet_backend: :socket

---

lib/mint/http1.ex
test/mint/http1/conn_test.exs
test/mint/http2/integration_test.exs

recv/3 did not correctly handle HTTP/1.0 style responses where the end
of the responses is signalled by the connection closing.
Fixes https://github.com/keathley/finch/issues/111.

Handle connection closed in recv/3

---

lib/mint/http1.ex

- see https://github.com/elixir-mint/mint/issues/301
Also related: https://github.com/elixir-mint/mint/issues/272
Not sure if we should rename `:invalid_header_value` to something like `non_ascii_char_in_header_value`

Clarify that header_value is invalid due to non-ASCII chars

---

lib/mint/http.ex
lib/mint/http1.ex
lib/mint/http2.ex

Given Mint reached the 1.0 milestone, I don't think `@doc since` on pre-1.0 additions is useful but of course it doesn't hurt either.

Remove `@doc since:` for pre-1.0.0 functions

---

lib/mint/http2.ex
lib/mint/http2/frame.ex
test/mint/http2/conn_test.exs
test/mint/http2/frame_test.exs

Hello! :wave:
I'm a huge fan of Mint, thank y'all for maintaining it :slightly_smiling_face:
I've been eyeing [#106](https://github.com/elixir-mint/mint/issues/106) lately and I've been able to get HTTP/1 websockets going with just some minor hacks in [`NFIBrokerage/mint_web_socket`](https://github.com/NFIBrokerage/mint_web_socket). The HTTP/2 bootstrap extends rfc7540's SETTINGS parameters, though, so it looks like we'll need to some changes here to support HTTP/2.
Specifically [rfc8441](https://www.rfc-editor.org/rfc/rfc8441.html) adds a settings param SETTINGS_ENABLE_CONNECT_PROTOCOL with [a new code of `0x8`](https://www.rfc-editor.org/rfc/rfc8441.html#section-9.1) defaulting to `0`.
This PR adds a new `t:Mint.HTTP2.setting/0` `:enable_connect_protocol` defaulting to `false` and the …

support SETTINGS_ENABLE_CONNECT_PROTOCOL server-side setting

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs

Hi again :slightly_smiling_face:
Like #321, this PR is for the sake of HTTP/2 bootstrap for WebSockets.
This PR makes two changes:
- omit `:scheme` and `:path` pseudo-headers in `Mint.HTTP2.request/5` when the `method` is `"CONNECT"`
- sort pseudo-headers to the front of the headers list
- this allows one to pass pseudo-header(s) to `Mint.HTTP2.request/5`
For the first part, I was skimming around rfc7540's section on [the CONNECT method](https://datatracker.ietf.org/doc/html/rfc7540#section-8.3) and found a MUST for CONNECT requests:
> The ":scheme" and ":path" pseudo-header fields MUST be omitted.
The second part is for the sake of the WebSocket bootstrap: rfc8441's section on [extending the CONNECT method](https://datatracker.ietf.org/doc/html/rfc8441#section-4) adds "A new …

omit :scheme and :path pseudo-headers in HTTP/2 CONNECT

---

.formatter.exs
lib/mint/http2.ex
test/mint/http2/conn_test.exs
test/support/mint/http2/test_transport_send_timeout.ex

Hello, and thank you for the great library!
HTTP2 leaks open requests in some cases when there are errors raised in `HTTP2.request/5`.
I ran into this when hitting `:exceeds_window_size` and `:too_many_concurrent_requests` errors in production.
We get some of these errors during the normal operation of our service, and each one leaks a request. When this happens, we retry our request on a different HTTP2 connection, so the leak was not noticeable for a long time.
Unfortunately we can eventually end up with enough leaked requests so that every HTTP2 request will error with `:too_many_concurrent_requests`. This leaves the HTTP2 connection in a bad state where it will no longer work.
This PR introduces some logic to clean up these errored requests, and adds a few checks to the tests to …

Prevent open requests from leaking when HTTP2.request or HTTP2. stream_request_body return an error

---

lib/mint/core/conn.ex
lib/mint/http.ex
lib/mint/http1.ex
lib/mint/http2.ex
lib/mint/tunnel_proxy.ex
lib/mint/unsafe_proxy.ex
test/mint/tunnel_proxy_test.exs

When connecting over HTTPS the only way to talk with proxy server is sending and receiving headers on connect method.

Add proxy_headers field to HTTP structs and fill this field in tunnel proxy

---

lib/mint/http.ex
test/http_test.exs

@ericmj it seems like that could also be achieved by making `Mint.HTTP.conn_module` public, but I'm not sure about `UnsafeProxy`. Since it uses `Mint.HTTP1` under the hood should we return `Mint.HTTP1?` `UnsafeProxy`? I don't really know what `UnsafeProxy` gets used for, guessing non-https proxying

add Mint.HTTP.module/1 to describe the conn module given a conn

---

test/mint/integration_test.exs
test/support/mint/dst_and_isrg.pem

As discussed in #328, this adds an integration test for the Let's Encrypt long chain handling on OTP 23.3 (prior to 23.3.4.5) and 24.0 (prior to 24.0.4).

Let's Encrypt long chain integration test

---

test/mint/core/transport/ssl_test.exs
test/mint/http1/integration_test.exs
test/mint/http2/conn_test.exs
test/mint/integration_test.exs
test/mint/unix_socket_test.exs

```
[warning] Description: 'Authenticity is not established by certificate path validation'
Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'
```
See: https://github.com/erlang/otp/issues/5352.

Silence certificate path validation warnings

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs

I found an odd scenario where a connection that is [closed for writing](https://github.com/elixir-mint/mint/blob/cf3ecabd16dc5a461e7e88919bef6508d553c0d5/lib/mint/http2.ex#L31-L32) will fail to `Mint.HTTP2.stream/2` any DATA frames that come in after the connection becomes read-only.
I can attach the pcap if you'd like but since all that takes a bunch of work I've added a screenshot of the wireshark view of the scenario I found that triggers the behavior:
In this case a request opens up and sends some data. Then the server sends a GOAWAY (no error) that closes the connection for writing, and then it finishes out the request by sending the response HEADERS and a DATA frame (with the end stream flag). Mint parses that HEADERS into the appropriate `[{:headers, ref, headers}, {:status, ref, …

HTTP/2: respect closed-for-writing when streaming data frames

---

lib/mint/http2.ex

The links to http2-spec are giving 404. 
I used the link to https://httpwg.org/specs/rfc7540.html as oppose to https://datatracker.ietf.org/doc/html/rfc7540 because it's used in https://http2.github.io main page.

Doc update dead links to RFC 7540

---

lib/mint/http2.ex
lib/mint/http2/frame.ex
test/mint/http2/frame_test.exs

Fixes the deprecation warnings for Elixir >= 1.14.
Also removed unused `use Bitwise` in `http2.ex`.

Use `import Bitwise` instead of `use Bitwise`

---

lib/mint/http2.ex

This PR corrects the documentation for the `HTTP2.get_window_size/2` function.
This function only exists in the `HTTP2` module, and pattern matches on the `:request` atom instead of `:request_ref`
https://github.com/elixir-mint/mint/blob/e7199d1163e5a8a1b0001cacc93063e866dbaa35/lib/mint/http2.ex#L759-L768

Correct `get_window_size/2` docs

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs
test/support/mint/http2/test_helpers.ex

Properly close socket on erroneous connection

---

lib/mint/http1.ex

The same way we do in `HTTP2.request/5`. Noticed it through dialyzer while passing a map of `headers` instead of a list.

Check argument types on `HTTP1.request/5`

---

lib/mint/core/transport/ssl.ex
lib/mint/http.ex
test/mint/integration_test.exs

- Resolves https://github.com/elixir-mint/mint/issues/377
- [`:public_key.cacerts_get/0`](https://www.erlang.org/doc/man/public_key.html#cacerts_get-0) returns [`combined_cert`](https://www.erlang.org/doc/man/public_key.html#type-combined_cert) which contains both the undecoded binary and the decoded `#'OTPCertificate'{}`
- While calling [`:public_key.pkix_decode_cert`](https://www.erlang.org/doc/man/public_key.html#pkix_decode_cert-2) with `:plain` returns `#'Certificate'{}`, both `#'OTPCertificate'{}` and `#'Certificate'{}` share very similar structure ([document](https://www.erlang.org/doc/apps/public_key/public_key_records.html#pkix-certificates)) and they both have `subjectPublicKeyInfo` and `validity`. Since we only depends on those 2 data to verify the certificates, just passing …

Skip calling pkix_decode_cert if the certs are already of tuple types

---

test/mint/http2/integration_test.exs

twitter redirects requests to `/` to feed cookie
```
> GET / HTTP/1.1
> Host: twitter.com
> User-Agent: curl/7.86.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< date: Wed, 10 May 2023 22:27:45 GMT
< perf: 7626143928
< vary: Accept
< server: tsa_f
< location: /
< set-cookie: guest_id=DONTHACKME; Max-Age=34214400; Expires=Sun, 09 Jun 2024 22:27:45 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
< content-type: text/plain; charset=utf-8
< x-powered-by: Express
< cache-control: no-cache, no-store, max-age=0
< content-length: 23
< x-transaction-id: 7f46533dbc8f17ff
< strict-transport-security: max-age=631138519
< x-response-time: 110
< x-connection-hash: f8c483d519f1efdc5bbcf97d82c0e5b8d4b7e532dd4fca239b59d9557a586213
```
I suspect we DOSing `httpbin` with CI.

Allow 302 status for twitter integration test

---

pages/Decompression.md

First of all, we can't use `:zlib.unzip/1` for deflate. If anything, it's `:zlib.uncompress/1`:
```elixir
iex> Req.get!("http://httpbin.org/deflate", raw: true).body |> :zlib.unzip()
** (ErlangError) Erlang error: :data_error
:zlib.inflate_nif(#Reference<0.3067689971.3529113605.174556>, 8192, 16384, 0)
:zlib.dequeue_all_chunks_1/3
:zlib.inflate/3
:zlib.unzip/1
iex:3: (file)
iex> Req.get!("http://httpbin.org/deflate", raw: true).body |> :zlib.uncompress()
"{\n  \"deflated\": true, \n  \"headers\": {\n    \"Accept-Encoding\": \"zstd, br, gzip\", \n    \"Host\": \"httpbin.org\", \n    \"User-Agent\": \"req/0.3.11\", \n    \"X-Amzn-Trace-Id\": \"Root=1-64d6b50d-4c634ab23ae6d5fe3dab6694\"\n  }, \n  \"method\": \"GET\", \n  \"origin\": \"89.73.45.237\"\n}\n"
```
But I don't think it's quite …

Update Decompression.md - drop deflate, mention zstd

---

docker-compose.yml

While attempting to add a naive "Happy Eyeballs" option for testing and experimentation, I encountered a "permission denied" error when running the docker-compose command. It was not immediately apparent that SELinux was the cause of the issue, making it challenging to identify the root cause.
To resolve this issue, this commit adds the `:z` mount option, which ensures SELinux compatibility by addressing the permission issues caused by SELinux when the Caddyfile is mounted without the appropriate label.
It's important to note that this change should only affect systems with SELinux enabled.

Ensure correct SELinux labeling of container files on SELinux enabled systems.

---

lib/mint/http.ex

See #410. I'm trying to improve the documentation about how `Mint.HTTP.open?/2` behaves for the different values of `type`.
@whatyouhide wdyt?

Clarify the `type` parameter of `Mint.HTTP.open?/2`

---

lib/mint/core/transport/ssl.ex
test/mint/core/transport/ssl_test.exs

Hey there
I think there's a bug in the OTP so I've opened an issue there: https://github.com/erlang/otp/issues/7968. I'm not sure they see it as a bug and how long it may take to fix this. Maybe it is not a bug for Erlang after all but it sure is for the Elixir world. And Mint is one place where it could be fixed. There's also a discussion on the [Elixir Forum](https://elixirforum.com/t/flame-k8s-backend-a-flame-backend-for-kubernetes/60346/3) about this. But let me quickly state the problem here, too.
The problem occurs when trying connect to an IP address over SSL where the server offers a certificate with its IP address in the "subject alternate names" extension. This is often the case when connecting to a Kubernetes API Server from within Kubernetes (hence the discussion on the …

Add `match_fun` clause to deal with ip addresses in TLS handshake

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs

There is some low-hanging fruit to improve the time it takes to open a new request with HTTP/2 by avoiding `URI.default_port/1` and `String.upcase/1` calls.
With some very un-scientific `:timer.tc/1` benchmarking I see these changes reduce the time it takes to complete a `Mint.HTTP2.request/5` call (passing `:stream` as the data argument) from 12.8ms to 2.5ms.

Optimize HTTP/2 request creation

---

lib/mint/core/util.ex
lib/mint/http1.ex
lib/mint/http1/parse.ex
lib/mint/http1/response.ex
lib/mint/http2.ex

This PR removes calls to Mint's original `downcase_ascii/1` which was found to be slower than Elixir's stock downcase with the `:ascii` option.
Closes #420 
I unrolled HTTP1.Parser.header_name/1's atom case for clarity, as inline pipes on the same line can be hard to read, I hope this is okay.

Replace Util.downcase_ascii with String.downcase(&1, :ascii)

---

lib/mint/core/transport/ssl.ex
lib/mint/core/transport/tcp.ex
lib/mint/http.ex
test/mint/core/transport/ssl_test.exs
test/mint/core/transport/tcp_test.exs

Add :inet4 transport option to disable IPv4 fallback

---

lib/mint/core/conn.ex
lib/mint/http.ex
lib/mint/http1.ex
lib/mint/http2.ex
lib/mint/unsafe_proxy.ex

Deprecate :read_write option on HTTP.open?/2

---

lib/mint/core/transport/ssl.ex

Removes the cost of calling `Code.ensure_loaded?/1` every time that credentials are not provided.

Check whether CAStore is available in compile-time

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs

When the stream state is local_half_closed and an end_stream flag is received, the stream can be terminated normally without RST_STREAM.
Closes #433.
I still didn't work on integration tests, and while current tests kind of cover this feature, I'll add a specific test for it.

Don't send RST_STREAM when not needed

---

.dialyzer_ignore.exs
README.md
lib/mint/core/transport/ssl.ex
mix.exs

The OTP team no longer supports Erlang versions earlier than 25+, so we can assuming that `:public_key.cacerts_get/0` is available and only fallback to `CAStore` if not.
This also solves a bug in that Req/Finch/Mint do not work inside escripts by default (because inside an escript you cannot access the priv dir of an application).

Default to using Erlang certificates store

---

README.md

This should switch the CI badge GitHub badge.

Fix incorrect CI badge which still point to Travis CI

---

docker-compose.yml
test/docker/tinyproxy-auth/Dockerfile
test/docker/tinyproxy/Dockerfile

This PR resolves the following error when using `podman-compose`:
Error: short-name "caddy:2.6.4-alpine" did not resolve to an alias and
no unqualified-search registries are defined in
"/etc/containers/registries.conf"
We also bump the Docker image for Caddy and Alpine Linux.

Fix cannot build Docker images using Podman Compose

---

test/mint/http1/integration_test.exs

This should resolve the errors when excluding test with :requires_internet_connection tag for http1 tests using the following command.
mix test --exclude requires_internet_connection

Fix http1 integration tests missing :requires_internet_connection tag

---

README.md

This PR updates the console markups so we can we can quickly click and copy them.

Rewrite the contributing and test docs

---

lib/mint/http2/frame.ex
test/mint/http2/frame_test.exs

Sometimes webservers respond with custom error codes which causes a FunctionClauseError in the humanize_error_code function. This change adds a generic case of the function that handles those cases.
Closes https://github.com/elixir-mint/mint/issues/437.

Add generic :custom_error case to humanize_error_code.

---

.github/workflows/main.yml

Not completely sure what the CI/coverage strategy is but it seemed like: Test these old versions and the newest one! So, I thought I'd upgrade the newest one.
Didn't upgrade the runner os as erlang 23 is only covered by ubuntu 20.04: https://github.com/erlef/setup-beam?tab=readme-ov-file#compatibility-between-operating-system-and-erlangotp
This will reach EOL in a couple of months. So, testing against erlang 23 will be quite a bit tougher then.

Run CI against erlang 27.1

---

lib/mint/http1.ex
lib/mint/http1/request.ex
test/mint/http1/conn_test.exs
test/mint/http1/request_test.exs

As discussed in https://github.com/elixir-mint/mint/issues/453
I tried to follow the guidance of `case_sensitive_headers` so
that these options are treated somewhat similarly.
I tried to keep with the patterns of surrounding code, if you want anything changed/I missed something - happy to do so!
In a separate commit I also included a small nicety as I saw the definition of the mint user agent duplicated over the tests. Happy to roll that back though.
Some questions/remarks inline.
Thanks for all your work! :green_heart: 
Tasks left for me:

Allow not validating target

---

lib/mint/http.ex

Most outside documenation (Finch, Req) links just to `Mint.HTTP.connect/4` for documentation. That makes it somewhat hard to find both the case insesntitive header options as well as the not validating target options.
Not sure it's worth duplicating them there, so I figured I'd just point to them - even if HTTP2 has no custom options as of now.
That's, of course, debatable. So, happy about feedback/improvements :)
Thank you!

Add documentation note about protocol specific options to Mint.HTTP.connect/4

---

lib/mint/http.ex

Clarifies the behavior from https://github.com/elixir-mint/mint/issues/152.

Clarify behavior of Mint.HTTP.stream/3

---

lib/mint/http.ex

Just upgraded to Mint 1.7 and started getting errors whenever trying to use it - 
```
** (UndefinedFunctionError) function Mint.HTTP1.open/2 is undefined or private. Did you mean:
* open?/1
* open?/2
(mint 1.7.0) Mint.HTTP1.open(%Mint.HTTP1{host: "hex.pm", port: 443, request: nil, streaming_request: nil, socket: {:sslsocket, {:gen_tcp, #Port<0.148>, :tls_connection, :undefined}, [#PID<0.7456.0>, #PID<0.7455.0>]}, transport: Mint.Core.Transport.SSL, mode: :passive, scheme_as_string: "https", case_sensitive_headers: false, skip_target_validation: false, requests: {[], []}, state: :open, buffer: "", proxy_headers: [], private: %{}, log: false}, :write)
(finch 0.19.0) lib/finch/http1/pool.ex:283: Finch.HTTP1.Pool.transfer_if_open/3
(finch 0.19.0) lib/finch/http1/pool.ex:70: anonymous fn/10 in …
```

fix: fix delegation of `open?` function to use the same function name

---

README.md
test/mint/http1/integration_test.exs
test/mint/http2/integration_test.exs
test/mint/integration_test.exs
test/mint/unix_socket_test.exs

Fix all integration tests
