elixir-mint/mint

lib/xhttp1/conn.ex

I got bit by this in Redix or Xandra, I don't remember, but I think `with` makes this so easy to handle that it's not worth not handling it :D

Handle possible errors with transport.setopts and transport.getopts

---

lib/xhttp2/conn.ex
test/xhttp2/conn_test.exs

Add XHTTP2.Conn.stream_request_body/3

---

lib/xhttp2/frame.ex

The error first popped up here: https://travis-ci.org/ericmj/xhttp/builds/353112165. The spec says that unknown paramters should be ignored, we were crashing on those instead.

Fix a bug when decoding HTTP/2 SETTINGS parameters

---

lib/xhttp/conn_behaviour.ex
lib/xhttp1/conn.ex
lib/xhttp2/conn.ex
lib/xhttpn/conn.ex
test/xhttp1/conn_test.exs
test/xhttp1/integration_test.exs
test/xhttp2/conn_test.exs

Add conn behaviour

---

lib/xhttp/unsafe_proxy.ex
lib/xhttp1.ex
lib/xhttp2.ex
lib/xhttp2/frame.ex
lib/xhttp_core/conn.ex
lib/xhttp_core/transport/ssl.ex
lib/xhttp_core/transport/tcp.ex
lib/xhttp_core/util.ex
mix.exs
mix.lock

@ericmj I started with just HTTP/2 docs. Most of the stuff will be similar for XHTTP and XHTTP1, so I will see if stuff can be extracted to XHTTP and referenced from these modules. But I wanted to start slower :)
I also left a few TODOs in the source, would love if we could discuss those.

XHTTP2 docs

---

lib/mint/http1/request.ex
lib/mint/http2.ex
test/mint/http1/request_test.exs

Add the the correct value of the default User-Agent header

---

lib/mint/http.ex
lib/mint/http1.ex
lib/mint/http2.ex

No point in documenting this until the proxy modules or at least Negotiate is documented.

Do not document connection upgrade

---

lib/mint/http1.ex
test/mint/http1/conn_test.exs
test/support/mint/http1/test_helpers.ex

Return accumulated responses on error

---

README.md

Remove outdated information from README

---

lib/mint/http2.ex

@ericmj thoughts on this? Do you think it makes things easier or harder?

Cut out a few lines of code through some metapgramming

---

lib/mint/core/util.ex
lib/mint/http1/request.ex
lib/mint/http2.ex

Not sure this is worth it and if it actually improve things and makes them cleaner, wdyt?

Extract put_new_header/3 into Mint.Core.Util

---

lib/mint/http.ex

Add examples for improved cipher interop

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs

Closes #119.
Before this commit, we didn't check for the client's max concurrent streams limit on the client side when HEADERS for a promised stream would come. Now we do that, and send an RST_STREAM with error code REFUSED_STREAM if the server tries to open a stream that goes over the client's limit.
We also do some more checks on the stream ID of a promised stream, as an additional security measure.

Check for client's max concurrent streams limit in HTTP/2

---

lib/mint/core/conn.ex
lib/mint/http.ex
lib/mint/http1.ex
lib/mint/http2.ex
lib/mint/unsafe_proxy.ex
test/mint/http1/conn_test.exs
test/mint/http2/conn_test.exs

Add the open_request_count/1 function to  connections

---

lib/mint/core/transport/ssl.ex
lib/mint/core/transport/tcp.ex
lib/mint/transport_error.ex
test/mint/transport_error_test.exs

\cc @wojtekmach, thanks for the suggestions! 💟

Simplify the Mint.TransportError exception and add tests for it

---

lib/mint/tunnel_proxy.ex

We were not handling the `{:error, conn, reason}` case but at the same time we were not using `conn` in `handle_responses/4`, so I removed the passing around of the connection to make things simpler.

Fix a bug in Mint.TunnelProxy

---

.travis.yml
test/mint/http1/integration_test.exs
test/mint/integration_test.exs
test/mint/transport_error_test.exs

Fix tests on OTP 21.3

---

lib/mint/core/transport/ssl.ex
mix.exs
mix.lock

I'm working on making this work on CI but it takes a long time, so in the meantime we can run this locally :). FWIW, this passes right now!

Add support for "mix dialyzer"

---

mix.exs
src/mint_shims.erl

Remove dependency on inets

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs

No error on graceful transport close in HTTP/2

---

CHANGELOG.md

Add an entry for v0.2.0 in the CHANGELOG

---

lib/mint/http.ex

Update Protocol negotiation section

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs

This change required to reword the way we handle incoming `HEADERS` (plus possible `CONTINUATION`) frames in HTTP/2. Before this commit, we would decode the headers and then for example check that the :status header was present.
Now, we need to track whether the first bunch of headers (the *request* headers) were received for each stream. If they were received, then the next headers that come for that stream have to be trailing headers and have to have the `END_STREAM` flag set (otherwise we do a protocol error).

Support trailing response headers in HTTP/2

---

lib/mint/core/conn.ex
lib/mint/http.ex
lib/mint/http1.ex
lib/mint/http1/request.ex
lib/mint/http2.ex
lib/mint/unsafe_proxy.ex
test/mint/http1/conn_test.exs
test/mint/http2/conn_test.exs

Add support for trailing headers in HTTP requests

---

lib/mint/tunnel_proxy.ex
test/mint/tunnel_proxy_test.exs
test/support/mint/http1/test_helpers.ex

Ensure only relevant socket messages are matched

---

lib/mint/core/util.ex
lib/mint/http.ex
lib/mint/http1.ex
lib/mint/http2.ex
test/mint/http2/conn_test.exs

Add default content-length header in HTTP/2

---

lib/mint/http1.ex
test/mint/http1/conn_test.exs

Return full, uncombined chunks in :data responses

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs

Concatenate values for the Cookie header

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs
test/mint/integration_test.exs
test/mint/tunnel_proxy_test.exs

Don't send WINDOW_UPDATE when the window size increment would be 0

---

.github/workflows/main.yml
lib/mint/core/util.ex
lib/mint/http.ex
test/mint/http1/conn_test.exs
test/mint/http2/conn_test.exs

Add the Mint.HTTP.is_connection_message/2 guard

---

lib/mint/core/transport/ssl.ex

It also fixes a race condition which could send
messages out of order to the transferred process.

Return {:error, :closed} if SSL is closed on transfer

---

lib/mint/http.ex

Fix minor typo

---

lib/mint/http.ex

Fix :partial_chain property in the docs

---

mix.exs

Use spdx short identifier

---

lib/mint/negotiate.ex

Handle transport errors in ALPN protocol negotiation

---

lib/mint/http1.ex
test/mint/http1/conn_test.exs

This PR allows request body streaming to be used to send multiple requests on the same conn.
The current behaviour is to raise a `FunctionClauseError` if multiple streamed requests are sent on the same conn by the following steps:
```elixir
{:ok, conn, ref1} = HTTP1.request(conn, "GET", "/", [], :stream)
{:ok, conn} = HTTP1.stream_request_body(conn, ref1, body1)
{:ok, conn} = HTTP1.stream_request_body(conn, ref1, :eof)
{:ok, conn, ref2} = HTTP1.request(conn, "GET", "/", [], :stream)
{:ok, conn} = HTTP1.stream_request_body(conn, ref2, body2)
```
The last statement will raise the error because it attempts to stream based on the state of `conn.request`, which refers to `ref1`, rather than the request with `ref2`.
The change in this PR is to make state & ref checks against the **last queued …

Support queue of streamed HTTP1 requests

---

.github/workflows/main.yml
mix.lock

I just used less steps (environment!) and added a check for unused dependencies, which caught Earmark :)

Streamline CI

---

.github/workflows/main.yml
lib/mint/core/conn.ex
lib/mint/core/transport/ssl.ex
lib/mint/core/util.ex
lib/mint/http.ex
lib/mint/http1.ex
lib/mint/http2.ex
test/mint/http2/integration_test.exs
test/mint/integration_test.exs

Make get_socket/1 public API

---

.github/workflows/main.yml
lib/mint/core/transport/ssl.ex
lib/mint/http.ex
test/mint/integration_test.exs
test/support/mint/http1/test_server.ex

Filter options incompatible with TLS 1.3

---

lib/mint/core/transport/ssl.ex
lib/mint/http.ex
test/mint/core/transport/ssl_test.exs
test/mint/http2/integration_test.exs

Implement cipher filtering based on TLS version and available crypto lib

---

lib/mint/core/transport/ssl.ex

* Mix was complaining when compiling Mint as a dependency if `:castore` was not in the dependencies too. Solved this by not using `CAstore` as a compile-time module reference, but making it dynamic instead.
* **Unrelated refactor**: I just used `Keyword.put_new/3` and `Keyword.put_new_lazy/3` in favor of some `if` checks in `Mint.Core.Transport.SSL`.

Fix compilation warnings around CAStore

---

lib/mint/core/transport/ssl.ex
lib/mint/http.ex

Mention OTP25+ cert management in errors and docs

---

README.md
docker-compose.yml
lib/mint/http.ex
test/mint/http1/integration_test.exs
test/mint/http2/conn_test.exs
test/mint/http2/integration_test.exs
test/mint/integration_test.exs
test/mint/tunnel_proxy_test.exs

Closes https://github.com/elixir-mint/mint/issues/265.
Closes https://github.com/elixir-mint/mint/issues/340.
🤞

Get tests passing again

---

lib/mint/http.ex
lib/mint/http2.ex
test/mint/http2/conn_test.exs
test/mint/http2/integration_test.exs

Add support for interim responses in HTTP/2

---

lib/mint/core/util.ex
lib/mint/http.ex
test/mint/http2/integration_test.exs
test/mint/unsafe_proxy_test.exs

Fix is_connection_message/2 guard for unsafe proxy

---

lib/mint/http2.ex
test/mint/http2/conn_test.exs
test/support/mint/http2/test_server.ex

Handle first server SETTINGS frame async

---

lib/mint/http2.ex

Closes https://github.com/elixir-mint/mint/issues/397.

Don't log GOAWAY every time

---

lib/mint/tunnel_proxy.ex

Fixes https://github.com/elixir-mint/mint/issues/438#issue-2374947979
See https://github.com/elixir-mint/mint/issues/438#issuecomment-2630421636 to why this change makes sense
I would be happy if the tests for this could be run with the CI, as I don't have anything Docker related set-up on my machine.

Wrap TunnelProxy errors

---

pages/Decompression.md

Fix typo in the "Decompression" guide
